### ISSUE TITLE
Query secuence crashing OrionLD

### ISSUE THREAD

**Issue by mainakae** [FIWARE/context.Orion-LD#65] opened 2019-05-10 07:42 UTC
Hi, and congratulations for the great work with OrionLD!

I've been testing the new broker and have found a really odd sequence that utterly crashes the broker. It even won't go back up after restarting the docker container.

The sequence is easy: with a mint new container (won't work with a previously existing container which has answered queries) launch two queries in sequence:

1. `GET http://{{orion}}/ngsi-ld/ex/v1/version`
2. `POST http://{{orion}}/ngsi-ld/v1/entities` with the following payload and headers:

```json
{
    "@context": [
            "http://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld",
            "http://schema.lab.fiware.org/ld/jsonldcontext.jsonld"
        ],
    "id": "urn:ngsi-ld:Room:Room1",
    "type": "Room",
    "temperature": {
        "value": 23,
        "type": "Property",
        "unitCode": "C"
    },
    "pressure": {
        "value": 720,
        "type": "Property",
        "unitCode": "mm Hg"
    }
}
```

and for headers in the second query `Content-Type: application/ld+json`

Hope this mystery unveils something worth fixing back there ;)

Best regards,
Pedro.

**Comment by tanktoo** [comment] 2019-05-10 09:46
I can confirm this. Happens with my version too.
`{
    "branch": "bug/136.ngsild_issue_0043_ignore",
    "kbase version": "0.2",
    "kalloc version": "0.2",
    "kjson version": "0.2"
}`
Response of first query as above. Second query results in crash. Without the version query before the second works as expected.

**Comment by kzangeli** [comment] 2019-05-10 09:50
Ok!
Will look into this asap.
A little busy today but this got to the top three of my current ToDo list.
Thank you for reporting!

**Comment by tanktoo** [comment] 2019-05-10 09:52
[issue65.log](https://github.com/FIWARE/context.Orion-LD/files/3165920/issue65.log)
My log file with debug mode.

**Comment by kzangeli** [comment] 2019-05-10 10:59
Unfortunately, the issue doesn't appear in my environment :(
Are both of you using docker?

**Comment by tanktoo** [comment] 2019-05-10 11:43
I use docker yes.

**Comment by mainakae** [comment] 2019-05-10 12:22
Me too!, and not only for testing.

**Comment by kzangeli** [comment] 2019-05-13 14:42
Just tried this in docker and ... no problem :( 
This is what I did:

1. Start orionld in an xterm
```
% orionld -fg  -t 0-255 -logLevel DEBUG
```
2. In another xterm, run version and create an entity:
```
root@f0400de28d3c:/opt/orion# curl localhost:1026/ngsi-ld/ex/v1/version
{
  "branch": "hardening/137.toIx-in-func-test",
  "kbase version": "0.2",
  "kalloc version": "0.2",
  "kjson version": "0.2"
}
root@f0400de28d3c:/opt/orion# payload='{
>     "@context": [
>             "http://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld",
>             "http://schema.lab.fiware.org/ld/jsonldcontext.jsonld"
>         ],
>     "id": "urn:ngsi-ld:Room:Room1",
>     "type": "Room",
>     "temperature": {
>         "value": 23,
>         "type": "Property",
>         "unitCode": "C"
>     },
>     "pressure": {
>         "value": 720,
>         "type": "Property",
>         "unitCode": "mm Hg"
>     }
> }'
root@f0400de28d3c:/opt/orion# curl localhost:1026/ngsi-ld/v1/entities -H "Content-Type: application/ld+json" -d "$payload"
```

It worked just fine. I also did a GET on the entity after creation.

**Comment by kzangeli** [comment] 2019-05-13 14:44
```
/opt/orion# curl "http://localhost:1026/ngsi-ld/v1/entities?type=Room&prettyPrint=yes"
[
  {
    "id": "urn:ngsi-ld:Room:Room1",
    "type": "Room",
    "https://uri.fiware.org/ns/datamodels/pressure": {
      "type": "Property",
      "value": 720.000000,
      "unitCode": "mm Hg"
    },
    "https://uri.fiware.org/ns/datamodels/temperature": {
      "type": "Property",
      "value": 23.000000,
      "unitCode": "C"
    },
    "@context": [
      "http://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld",
      "http://schema.lab.fiware.org/ld/jsonldcontext.jsonld"
    ]
  }
]
```

**Comment by tanktoo** [comment] 2019-05-13 16:03
That't interesting. I just tried it again with curl and it seems to work fine. Then I just started postman, sent both queries and it crashed again. I don't see a difference between postman command and curl...

**Comment by kzangeli** [comment] 2019-05-13 16:07
Might have to with really recent changes http -> https for the contexts. We are working on it right now.
Bad timing :))

**Comment by kzangeli** [comment] 2019-05-14 08:32
Closing this issue as it seems the problem is only seen using postman, not using curl.
A new issue will be opened about the postman problem.

**Closed by kzangeli** 2019-05-14 08:32 UTC
